name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      BUILD_GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: remove git auth
        run: git config --unset http.https://github.com/.extraheader
      - name: Configure Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          path: ./node_modules
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: build
        run: yarn build
