name: CI
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: remove git auth
        run: git config --unset http.https://github.com/.extraheader
      - name: Configure Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          path: ./node_modules
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: test
        run: yarn test:unit
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: remove git auth
        run: git config --unset http.https://github.com/.extraheader
      - name: Configure Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          path: ./node_modules
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: lint
        run: yarn lint
